package org.caesarj.ui.model;

import java.util.List;

import org.aspectj.asm.ProgramElementNode;
import org.aspectj.asm.ProgramElementNode.Kind;
import org.aspectj.bridge.ISourceLocation;

/**
 * Adds additional methods needed in NodeEliminator Visitor.
 * @see isToRemove
 * 
 * @author Ivica Aracic <ivica.aracic@bytelords.de>
 */
public class CaesarProgramElementNode extends ProgramElementNode {
    public CaesarProgramElementNode(
        String signature,
        Kind kind,
        List children
    ) {
        super(
            signature,
            kind,
            children
        );
    }
    
    public CaesarProgramElementNode(
        String signature,
        Kind kind,
        ISourceLocation sourceLocation,
        int modifiers,
        String formalComment,
        List children
    ) {
        super(
            signature,
            kind,
            sourceLocation,
            modifiers,
            formalComment,
            children
        );
    }
    
    
    /**
     * Support methods generated by caesar compiler should not be visible
     * in ASM. 
     * 
     * @return true if this node should be removed in final ASM
     */
	public boolean isToRemove() {
		return 
            getName().equals("_getBinding")
            || getName().equals("_getProviding")
            || getName().equals("_getProvidingReference")
            || getName().equals("_getWrappee");
	}
    
    
    public String toString() {        
        return "["+getKind()+"] "+getName();
    }
}
